name: CocoOlson
favicon: null
layout_spectrum: 0.7192366712260991
typography_spectrum: 0.6368828220292926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.988087160512805
  lightness: 0.3096365425735712
  saturation: 0.9250397600699216
  rhythmicContrast: 0.4404312854167074
purpose: []
