purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9250397600699216
  brandStrength: 0.988087160512805
  rhythmicContrast: 0.4404312854167074
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  lightness: 0.3096365425735712
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: CocoOlson
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4085106
layout_spectrum: 1
